
spring:
  application:
    name:
      ms-naissance
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /api
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public

