name: deploy application
run-name: ${{ github.actor }} is deploying project
on:
  push:
  workflow_dispatch:
env:
  GROUP: /opt/mes-naissances
  PROJECT: website-naissances
jobs:
  create-folder:
    name: Create folder on server
    runs-on: ubuntu-24.04
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p ${{env.GROUP}}/${{env.PROJECT}}

  build-project:
    runs-on: ubuntu-24.04
    needs: create-folder
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: build project
        run: |
          npm run build
      - name: Copy files on server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: dist
          target: ${{env.GROUP}}/${{env.PROJECT}}
          strip_components: 1
          overwrite: true
 